### PR TITLE
Deprecate use of deploy.json in favor of config/deploy.js. Closes #51

### LINKED ISSUE #51: Deprecate use of deploy.json in favor of config/deploy.js
- [x] Update README
- [x] Add deprecation warning in case of deploy.json being used

### PR DESCRIPTION
**Pull request by lukemelia**
* introduces a deprecate util
* provides the ConfigurationReader with the ui instance
* improves error message when config file is missing
* changes default value for --deploy-config-file option
* updates README

### CODE REVIEW

**Comment by samselikoff** [comment]
do I remember us saying we will eventually also support per-env files?

**Comment by samselikoff** [comment]
code looks great to me. What's customary here, should I actually pull down and try it? Or are the tests supposed to handle the behavior?

**Comment by achambers** [comment]
I believe it was agreed in one of the issues that we'd just have a single deploy.js file @samselikoff .

**Comment by danshultz** [comment]
@samselikoff - issue #46 has some comments regarding per env configs.

Regarding what is customary - I do what is necessary for me to be comfortable :+1:  the PR. Sometimes I pull down code to verify and probe around some use cases I'm unsure are handled. Usually however, I'm good to read through the code and don't need to pull it down and review.

**Comment by lukemelia** [comment]
Tests should handle it. We should have a manual smoke test as part of our release process.

If we make a mistake, we will fix or revert.

Someone go ahead and press the big green button.

**Comment by danshultz** [comment]
:+1: - I can't press the big green button but it looks good to me

**Comment by lukemelia** [comment]
@danshultz just invited you to the team

**Comment by danshultz** [comment]
Thanks PR merged

**Pull request merged**
