### PR TITLE
Another incorrect quote

### PR DESCRIPTION
**Pull request by knownasilya**
I promise this is the last one @achambers

### CODE REVIEW

**Comment by achambers** [comment]
Are you sure?

**Comment by knownasilya** [comment]
Looks good here: https://github.com/knownasilya/ember-cli-deploy/blob/patch-3/README.md

**Comment by achambers** [comment]
Okie.  Thanks.

FYI, The README is getting an overhaul in #59 anyway so no need to spend time on it.

**Comment by knownasilya** [comment]
Saw that after I made this changed, but this will be the last one.

**Comment by achambers** [comment]
Thanks for your input mate.

**Pull request merged**
