### PR TITLE
S3 walkthrough

### PR DESCRIPTION
**Pull request by pablobm**
So, I had some trouble understanding ember-cli-deploy the first time I got into it, not two months ago. I appreciate that a lot of work has gone into the documentation, and it ultimately helped me, but it took me a while to put the pieces together. Afterwards, it left me thinking of ways it could be improved.

Recently I had a chat with @achambers, who encouraged me to send a pull request if I could come up with something more concrete. It's a bit difficult to point at specific problems, so I thought I'd rather start writing a complete, step-by-step example on building a pipeline for a simple strategy.

Here's what I have been able to come up so far. It's not complete but, before polishing it (and adding one or two missing sections), I wanted to fly this past you.

  * Is this a good idea?
  * Does this have a place in the current documentation?
  * Is it factually correct? (After all, I'm just a newly-arrived user)

### CODE REVIEW

**Comment by ghedamat** [comment]
@pablobm thanks for this! we'll try to review shortly and provide feedback

**Comment by lukemelia** [comment]
Looks pretty awesome @pablobm! Thanks.

**Comment by pablobm** [comment]
Cool! Thanks. Sounds like approval to me. I'll complete/polish it. Stay tuned.

**Comment by LevelbossMike** [comment]
This is great! :tada:  Thanks a lot! :+1:

**Comment by pablobm** [comment]
OK, I'm happy enough with the content now. Thoughts?

**Comment by ghedamat** [comment]
@pablobm looks good, would you mind squashing the commits and target this branch  instead? https://github.com/ember-cli/ember-cli-deploy/tree/gh-pages-0.6.x-first-pass

we'd like to put this in the 0.6. docs

**Comment by pablobm** [comment]
Superseded by #352, as per @ghedamat's request.

**Pull request closed without merging**
