### PR TITLE
Make io.js work

### LINKED ISSUE #133: Not working with iojs
I created a new Ember CLI project, a new bucket on S3, and followed the instructions on the README to npm install ember-cli-deploy, ember-deploy-redis, and ember-deploy-s3. I also created `config/deploy.js` that's basically a copy of what's in the README. However, when I run `ember deploy` or `ember deploy --environment=development` it gets to this point and then freezes up and never recovers:

    $ ember deploy --environment=development
    version: 0.2.3
    Built project successfully. Stored in "dist/".

This happened with iojs v1.6.3. I upgraded to iojs v1.8.1 and this was still occurring. When I switch to node v0.12.2, however, things work fine.

Also, I tested the individual commands, and `ember deploy:index` works fine when I'm using iojs, but `ember deploy:assets` freezes up, so I'm guessing this might have to do with the s3 adapter?

EDIT: We might want to add a note to the README about this until it's fixed. It's definitely frustrating to run into when you're just getting started.

### PR DESCRIPTION
**Pull request by trym**
Fixes #133

### CODE REVIEW

**Comment by LevelbossMike** [comment]
wohoo! Thx a lot!

**Comment by cibernox** [comment]
@achambers can anyone cut a new release of this with the fix. I'd really love to deploy my app :+1:

**Comment by achambers** [comment]
Sure thing @cibernox. I'm in Spain at the moment but can do it next week
when I'm back. Otherwise, maybe @LevelBossMike can do it before then if you
need it urgently. It's definitely time for a release.

**Comment by cibernox** [comment]
@achambers Lucky you! Eat properly on my behalf!

**Comment by LevelbossMike** [comment]
@cibernox I'll do the release this weekend. most likely today. thx for the ping.

**Comment by LevelbossMike** [comment]
@cibernox 0.4.2 has just been released to npm.

**Comment by cibernox** [comment]
Thx. I was using it already from master and I confirm that works for me

**Pull request merged**
