### PR TITLE
display progress notification during deploy

### PR DESCRIPTION
**Pull request by ghedamat**
first pass at addressing #276 

Remaining TODOs:

* [x] add commandLine  option to disable progressBar
* [x] add configFile option as well
* [x] ideally figure out a way to resolve rendering issues as seen in the video 
* [x] test this out?
* [ ] update ember-cli-deploy-plugin version in core repos

http://gsnaps.s3.amazonaws.com/screencast_2016-01-08_14-54-36_0_edited.mp4

### CODE REVIEW

**Comment by ghedamat** [comment]
shall we make the progress thingy optional if `--verbose` is passed?

**Comment by lukemelia** [comment]
I don't want to rush this into 0.5.0. I'd suggest saving it for 0.5.1.

**Comment by ghedamat** [comment]
works for me :)

**Comment by seawatts** [comment]
Woo hoo this would be awesome!

**Comment by ghedamat** [comment]
current status
http://gsnaps.s3.amazonaws.com/screencast_2016-01-08_14-54-36_0_edited.mp4

we don't count `configure` hooks

we trigger a tick for each of the other hooks, in my demo app we have `10` ticks in total

it's still a bit "choppy" because some hooks are faster than other but I think it's not bad.

feedback is welcome

@lukemelia @achambers @seawatts

**Comment by ghedamat** [comment]
also, this currently runs also for `deploy:list` and `deploy:activate` and ends up looking quite weird.

maybe we should pass an option and do it only for `deploy`?

**Comment by ghedamat** [comment]
once we merge https://github.com/ember-cli-deploy/ember-cli-deploy-plugin/pull/6 and update the relevant plugins we should solve the overlap problem 

http://gsnaps.s3.amazonaws.com/screencast_2016-01-10_22-06-28_0_edited.mp4

**Comment by ghedamat** [comment]
Now with increased niceness
http://gsnaps.s3.amazonaws.com/screencast_2016-01-12_18-19-02_0_edited.mp4

(note that I'll have to add a tweak to `ember-cli-deploy-plugin` for this to work properly)

**Comment by seawatts** [comment]
:+1:

On Tue, Jan 12, 2016 at 3:21 PM, Mattia Gheda <notifications@github.com>
wrote:

> Now with increased niceness
> http://gsnaps.s3.amazonaws.com/screencast_2016-01-12_18-19-02_0_edited.mp4
>
> (note that I'll have to add a tweak to ember-cli-deploy-plugin for this
> to work properly)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-cli/ember-cli-deploy/pull/280#issuecomment-171096880>
> .
>



-- 
*Chris Watts* | Software Engineer | cwatts@simplymeasured.com

**Comment by stefanpenner** [comment]
fancy

**Comment by ghedamat** [comment]
@lukemelia @stefanpenner you might know this

what's the consensus on adding an emoji to a command line prompt? from experience I know it likely won't work on linux terminals, so I'm kind of against it but it would be cute (I was thinking of :rocket:)

**Comment by hhff** [comment]
:nail_care:

**Comment by lukemelia** [comment]
@ghedamat no idea of tech details of terminal emoji, but we could probably platform detect, I am :+1: :rocket: :exclamation:

**Comment by ghedamat** [comment]
@lukemelia I think we're ready for a final review, I added the aliases as requested and some test coverage

**Comment by ghedamat** [comment]
ok, to whom is interested, now I consider this ready

only thing to note is that from what I can tell ember-cli help won't print long aliases correctly (maybe this should be a separate PR) 

i.e.

`--show-progress` is aliased to `-p` and `--progress`

but the help is printed as

```
ember deploy <deployTarget> <options...>
  Deploys an ember-cli app
  --deploy-config-file (String) (Default: config/deploy.js)
  --verbose (Boolean) (Default: false)
  --activate (Boolean) (Default: false)
  --show-progress (Boolean) (Default: true)
    aliases: -p, -progress
```

it seems that when using it both `-progress` and `--progress` are being supported
see https://github.com/ember-cli/ember-cli/blob/282641ba662292afb40cb88cdf31557a3e4cc6b7/lib%2Futilities%2Fprint-command.js#L79

**Comment by lukemelia** [comment]
@ghedamat looks great! I have one last idea for your consideration. Shall we only default this to true if the command is being run from a terminal? Seems like we can check `process.stdout.isTTY` ([source](http://stackoverflow.com/questions/7080458/test-whether-the-actual-output-is-a-terminal-or-not-in-node-js))

**Comment by ghedamat** [comment]
@lukemelia done directly in the deploy command so that it's the default

minor problem is: if you use `.ember-cli` option that will override the default, but I don't see why one would force it to "true" as that's the standard behaviour anyway

**Comment by lukemelia** [comment]
Great work @ghedamat!

**Pull request merged**
