### PR TITLE
fixes to postBuildHook

### PR DESCRIPTION
**Pull request by ghedamat**

### CODE REVIEW

**Comment by ghedamat** [comment]
@lukemelia agreed, I'll try to see if I have some spare time to add some coverage this week

**Comment by ghedamat** [comment]
@lukemelia added some tests at least

let me know what you think!

**Comment by lukemelia** [comment]
Step in the right direction! OK to merge?

**Comment by ghedamat** [comment]
I think so, I caught another bug, now it seems to we working alright, let's merge and test in my app!

**Pull request merged**
