### PR TITLE
Add basic testing guide

### PR DESCRIPTION
**Pull request by ibroadfo**

### CODE REVIEW

**Comment by duizendnegen** [comment]
Seems good.
One thing: "Plugins aren't tested like regular ember addons." Might want to spend a word or two as to why they aren't. But that's optional.

**Comment by ibroadfo** [comment]
agreed, but i don't know why it's the case. :smile:

happy to include an explanation if someone lets me know.

**Comment by duizendnegen** [comment]
It's because the project is a bit of an edge case, it doesn't require a dummy app or an active Ember environment or whatever to do it's functioning - it just relies on stuff being built, then doing whatever with the built files.
In short, it runs in a *node* context, not in an *Ember* context. Maybe that's the best explanation.

Oh and if you could squash the commits into one commit, that would be awesome.

**Comment by LevelbossMike** [comment]
Great pr! Thx a lot! Would be cool if we could also add something about how we usally go about testing external services because a deployment plugin will most likely interact with an external s

**Comment by ibroadfo** [comment]
i'm assuming there'll be more to do so will delay squashing till all done

**Comment by ghedamat** [comment]
LGTM ! thanks @ibroadfo 

@LevelbossMike have all your concerns be addressed?

**Comment by LevelbossMike** [comment]
:+1: LGTM! Thanks again @ibroadfo

**Comment by ibroadfo** [comment]
:grinning: thanks for the notes @duizendnegen @LevelbossMike

**Pull request merged**
