### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by ef4**
This change:

 - adds jshinting to the test suite
 - makes jshint pass, including some dead code removal
 - fixes the test script definition so it properly expands and finds all tests

### CODE REVIEW

**Comment by ef4** [comment]
If you compare the test output of this branch vs the previous successful master build, you can see we were missing many tests before: [before](https://travis-ci.org/ember-cli/ember-cli-deploy/builds/101933732), [after](https://travis-ci.org/ember-cli/ember-cli-deploy/builds/103507318)

**Comment by lukemelia** [comment]
Ahh, the test matching bug just manifested itself in the most recent commit.

Thanks for that and the general cleanup @ef4!

**Comment by ef4** [comment]
That makes sense -- I was surprised that the tests were all passing if they really hadn't been running for a while!

**Comment by ghedamat** [comment]
@ef4 amazing! Thanks for this!

**Pull request merged**
