### PR TITLE
Update fingerprinting URL in README

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by lukemelia** [comment]
Thanks @wagenet.

@samselikoff how do we keep this kind of thing in sync with the new docs site?

**Comment by samselikoff** [comment]
I think we should scrap the readme and just it point to the site, and make sure the site encourages PRs (I've added the "Improve this page" link, hopefully that's enough).

If everyone gives it a :shipit:, we can add the link to the site + delete the readme. I already pulled the readme to the site so all the content should be there.

**Comment by LevelbossMike** [comment]
:+1: :shipit:

**Comment by samselikoff** [comment]
donezo

**Pull request merged**
