### PR TITLE
Correct upgrade documentation

### PR DESCRIPTION
**Pull request by backspace**
I’m not sure what the best answer is here. This is the simplest proposal. Perhaps a link to the 0.4-to-0.5 documentation is in order? Or maybe the duplication is desired, in which case I can restore it.

### CODE REVIEW

**Comment by lukemelia** [comment]
@backspace thanks for noticing this. I think it would be best to have two sections of this doc: 1) Upgrading an App from 0.5.X to 0.6.x and 2) Upgrading an App from 0.4.X to 0.6.x

**Comment by backspace** [comment]
Okay. How about this? It’s what was already there with changed headings haha

**Comment by ghedamat** [comment]
@backspace mind rebasing/resolving conflicts? thanks!

**Comment by backspace** [comment]
hmm, it appears [this has been superseded](https://github.com/ember-cli/ember-cli-deploy/blob/037c7ac06a041fe0aae9054a39b6bf6a21d9b32e/docs/v0.6.x/upgrading-apps.md)!

**Comment by ghedamat** [comment]
@backspace  seems good! Thanks anyway!

**Pull request closed without merging**
