### PR TITLE
https does not work on npmsearch

### PR DESCRIPTION
**Pull request by broerse**

### CODE REVIEW

**Comment by achambers** [comment]
@broerse I don't have a problem with https.

**Comment by LevelbossMike** [comment]
Does this really not work? I just checked this as well and the page loads normally for me.

**Comment by duizendnegen** [comment]
https also works just fine for me
Closing now, feel free to comment / open another PR if necessary

**Comment by broerse** [comment]
Perhaps it is a Chrome thing. https gives me `NET::ERR_CERT_AUTHORITY_INVALID`

**Comment by achambers** [comment]
I was accessing it in Chrome no problem.

**Comment by broerse** [comment]
It works in Edge so lets skip this PR. It is probably a bug.

**Pull request closed without merging**
