### PR TITLE
[#151] read manifestPrefix from config

### PR DESCRIPTION
**Pull request by pavloo**
Fixes https://github.com/ember-cli/ember-cli-deploy/issues/151
I'd appreciate if someone could give me some advise on how to implement tests ( if there are needed any :) )

### CODE REVIEW

**Comment by juggy** [comment]
@stefanpenner can we merge this?

**Comment by stefanpenner** [comment]
cc @lukemelia r?

**Comment by stefanpenner** [comment]
> @stefanpenner can we merge this?

seems like it needs tests, @juggy want to help him add tests?

**Comment by juggy** [comment]
There are currently no tests for the deploy task and well as the list task. The configuration is already tested here: https://github.com/pavloo/ember-cli-deploy/blob/custom-key-names/node-tests/unit/models/config-test.js#L12-L22

The tasks are not easily testable right now. Each part are tested (tag, adapters, etc) correctly and they all take a manifest as input.

**Comment by LevelbossMike** [comment]
This is great! Thanks a lot!

**Pull request merged**
