### PR TITLE
WIP: First draft of hooks for deployment pipeline.

### PR DESCRIPTION
**Pull request by LevelbossMike**
This is a first draft of providing the hook functionality discussed in https://github.com/ember-cli/ember-cli-deploy/pull/88 and https://github.com/ember-cli/ember-cli-deploy/issues/47.

This is the absolute minimal version of the discussed functionality and is WIP. 

I created a new utility class `DeploymentTask` which knows about hooks that can be registered by ember-cli-deploy-addons/plugins.

It should be trivial to refactor the existing code base to use hooks instead of the existing adapters. Which is also the right way into the direction of the `deployment-pipeline` discussed in https://github.com/ember-cli/ember-cli-deploy/issues/47.

Right now this could be used with the existing code base by adding methods that execute the respective hooks in the relevant tasks.

### CODE REVIEW

**Comment by ascot21** [comment]
What's the status on getting this merged in?  This would be really helpful.

**Comment by achambers** [comment]
Hi @ascot21.  This was a spike around how we might implement the pipeline functionality.  #130 is the PR that will most likely be merged in when it's ready.  It's under active development at the moment but is not yet ready.  This PR will make up the bulk of `v0.5.0`.  I am trialling using the branch behind #130 as we speak.  Feel free to do the same but be warned that changes are being made regularly.....Would be great to get your input on it though if possible.

**Comment by ascot21** [comment]
@achambers awesome thanks.  Didn't realize #130 had that in there. Will test it out.

**Comment by achambers** [comment]
Great.  Let us know how you get on.

**Comment by achambers** [comment]
And you can find the plugins I'm working on at https://github/zapnito

**Comment by LevelbossMike** [comment]
Closing in favor of https://github.com/ember-cli/ember-cli-deploy/pull/130

**Pull request closed without merging**
