### PR TITLE
Update package.json and README to reflect move to ember-cli org

### LINKED ISSUE #41: Update package name to ember-cli-deploy

### PR DESCRIPTION
**Pull request by achambers**
Closes #41

### CODE REVIEW

**Comment by lukemelia** [comment]
Travis issue seems related to https://github.com/travis-ci/travis-ci/issues/2698

**Comment by achambers** [comment]
Yeh, also this: http://stackoverflow.com/questions/27086684/travis-fails-finding-my-travis-yml

**Comment by achambers** [comment]
It looks like @LevelbossMike is still listed in the travis ci webhook which doesn't seem like it would do much good.

**Comment by achambers** [comment]
Hmm...Now it has me as the user in the webhooks settings.  Weird.  Not sure how that happened

**Pull request merged**
